---
## SSH Key Options
generate_ssh_keys: true
ssh_private_key_path: /opt/id_rsa
ssh_public_key_path: /opt/id_rsa.pub

# openshift_release_version needs to be formatted as a string
openshift_release: "4.13.1"
