galaxy_info:
  description: Deploys a basic RHACM Operator instance
  company: Red Hat

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - openshift
    
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
