---
- name: Setup operators and services on a Hub OpenShift Cluster for RHACM, GitOps (ArgoCD)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    output_lines: []
    #########################################
    
    ## Operator Management

    deploy_rhacm: false
    deploy_rh_gitops: false

    deploy_to_infra_nodes: true

  tasks:

    - name: Install Red Hat Advanced Cluster Management
      when: deploy_rhacm | bool
      ansible.builtin.include_role:
        name: deploy_rhacm_operator

    - name: Install Red Hat GitOps Operator
      when: deploy_rh_gitops | bool
      ansible.builtin.include_role:
        name: deploy_rh_gitops_operator

    - name: Print the Playbook output
      when: output_lines | length > 0
      ansible.builtin.debug:
        msg: "{{ output_lines }}"
