---
- name: Configure a Hub OpenShift Cluster for RHACM, GitOps (ArgoC)
  hosts: localhost
  connection: local
  gather_facts: false

  module_defaults:
    kubernetes.core.k8s_info:
      validate_certs: false
    kubernetes.core.k8s:
      validate_certs: false
    kubernetes.core.helm:
      validate_certs: false

  vars:
    #########################################
    output_lines: []

    configure_rhacm: true
    configure_rh_gitops: true

    # git_credential_type: ssh | basic
    scm_credential_type: basic
    scm_credential_username: user-1
    scm_credential_password: openshift
    scm_credential_private_key: ~/.ssh/id_rsa
    scm_credential_public_key: ~/.ssh/id_rsa.pub
    scm_repo_name: openshift-ztp

  tasks:
    - name: Configure RHACM
      when: configure_rhacm | bool
      ansible.builtin.include_role:
        name: configure_rhacm_oas

    - name: Configure ArgoCD/Red Hat GitOps for syncing Spoke Clusters
      when: configure_rh_gitops | bool
      ansible.builtin.include_role:
        name: configure_argocd

    - name: Print the Playbook output
      when: output_lines | length > 0
      ansible.builtin.debug:
        msg: "{{ output_lines }}"
